spring.application.name=ai-interviewer
server.port=8000


#DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_interviewer
spring.datasource.username=postgres
spring.datasource.password=securepassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


### API KEYS
openai.api.base-url=https://api.openai.com
openai.api.key=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
judge0.api.base-url=https://judge0-ce.p.rapidapi.com
judge0.api.rapid-key=2b4a19ef6bmshf9386222a489924p185989jsn416e5a13b142


# Security is disabled
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
