spring.application.name=ai-interviewer
server.port=8081


#DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_interviewer
spring.datasource.username=postgres
spring.datasource.password=securepassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


### API KEYS
openai.api.base-url=https://api.openai.com
openai.api.key=${OPENAI_API_KEY}

judge0.api.base-url=https://judge0-ce.p.rapidapi.com
judge0.api.rapid-key=${JUDGE0_API_KEY}
