spring.application.name=ai-interviewer
server.port=8081


#DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/ai_interviewer
spring.datasource.username=postgres
spring.datasource.password=securepassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration